layout: index
theme: jekyll-theme-cayman
title: [Basel Jayyusi]
description: [Mathematical Physics Student with an interest in Pure Mathematics]
mathjax: true
comments: true
categories: github jekyll
