theme: jekyll-theme-cayman
title: [Basel Jayyusi]
description: [Mathematical Physics Student with an interest in Pure Mathematics \\ 
E-Mail: bjayyusi@uwaterloo.ca]
layout: post
mathjax: true
comments: true
categories: github jekyll
