theme: jekyll-theme-cayman
title: [Basel Jayyusi]
description: [Mathematical Physics Student with an interest in Pure Mathematics]
email: bjayyusi@uwaterloo.ca
layout: post
mathjax: true
comments: true
categories: github jekyll
